import Foundation
import UIKit

struct PARAMS {
    static let ADDRESS             = "address"
    static let COMMENT_CONTENT     = "comment_content"
    static let COMMENT_NUM         = "comment_num"
    static let COMMENT_TIME        = "comment_time"
    static let EMAIL               = "email"
    static let HASH_TAG            = "hash_tag"
    static let ID                  = "id"
    static let ISSHOWING_MAP       = "isshowing_map"
    static let IS_BLOCK            = "is_block"
    static let IS_FRIEND           = "is_friend"
    static let IS_LIKE             = "is_like"
    static let IS_PET_LIKE         = "is_pet_like"
    static let IS_POST_LIKE        = "is_post_like"
    static let IS_PUBLIC           = "is_public"
    static let IS_SHARELOCATION    = "is_sharelocation"
    static let LAT                 = "lat"
    static let LOCATION_COUNT      = "location_count"
    static let LOGOUT              = "logout"
    static let LONG                = "long"
    static let MEDIA_RATIO         = "media_ratio"
    static let MEDIA_TYPE          = "media_type"
    static let MEDIA_URL           = "media_url"
    static let MESSAGE             = "message"
    static let NEWS_ID             = "news_id"
    static let OWNER_ID            = "owner_id"
    static let PASSWORD            = "password"
    static let PETS_INFO           = "pets_info"
    static let PET_BIRTH           = "pet_birth"
    static let PET_GENDER          = "pet_gender"
    static let PET_ID              = "pet_id"
    static let PET_KIND            = "pet_kind"
    static let PET_LIKE_NUM        = "pet_like_num"
    static let PET_NAME            = "pet_name"
    static let PET_PHOTO           = "pet_photo"
    static let PET_TYPE            = "pet_type"
    static let PHONE_NUMBER        = "phone_number"
    static let PIN_CODE            = "pin_code"
    static let POST_DES            = "post_des"
    static let POST_DETAIL         = "post_detail"
    static let POST_ID             = "post_id"
    static let POST_LIKE_NUM       = "post_like_num"
    static let POST_THUMB          = "post_thumb"
    static let POST_TIME           = "post_time"
    static let RADIUS              = "radius"
    static let REQUEST_TYPE        = "request_type"
    static let RESULTCODE          = "result_code"
    static let SELF_INTRO          = "self_intro"
    static let SERVICE_DESCRIPTION = "service_description"
    static let SERVICE_ID          = "service_id"
    static let SERVICE_PRICE       = "service_price"
    static let SERVICE_STATUS      = "service_status"
    static let SERVICE_TIME        = "service_time"
    static let SERVICE_TYPE        = "service_type"
    static let STRIPE_ACCOUNT_ID   = "stripe_account_id"
    static let TAB_NAME            = "tab_name"
    static let TOKEN               = "token"
    static let USER_ID             = "user_id"
    static let USER_INFO           = "user_info"
    static let USER_LOCATION       = "user_location"
    static let USER_NAME           = "user_name"
    static let USER_PHOTO          = "user_photo"
    static let USER_URL            = "user_url"
    static let USER_DES            = "user_description"
    static let LOCATION_ID = "location_id"
    static let POST_CONTENT = "post_content"
    static let MARK_ID = "mark_id"
    static let MARK_NAME = "mark_name"
    static let MARK_IMAGE = "mark_image"
    static let MARK_DESCRIPTION = "mark_description"
    static let LOCACTION_ADDRESS = "location_address"
    static let LOCATION_LAT = "location_lat"
    static let LOCATION_LANG = "location_lang"
    static let LOCATION_DESCRIPTION = "location_description"
    static let LOCATION_NAME = "location_name"
    static let LOCATION_IMAGE = "location_image"
    static let IS_LOCACTION_LIKE = "is_location_like"
    static let HAS_NEW_NOTI = "has_new_noti"
    static let LOCATION_MEMO = "location_memo"
    static let LAST_UPDATED = "last_updated"
    static let UUID = "uuid"
}

struct Messages {
    static let LOGIN                    = "ログイン"
    static let ACCOUNT                    = "アカウント"
    static let ACCEPT                    = "受け入れる"
    static let ACCEPTED                  = "受け入れ"
    static let ADD_LOCATION              = "あなたの場所を追加します。"
    static let ADD_NEW_PET               = "新ペットを追加"
    static let ADD_PHOTO                 = "写真を追加します。"
    static let ADD_YOUR_PET              = "ペット追加します"
    static let ALBUM                     = "アルバム"
    static let BIRTHDAY                  = "誕生日"
    static let BIRTHDAY_REQUIRE          = "誕生日を追加します。"
    static let BLOCKED_USER_LIST         = "ブロックされたユーザー"
    static let BLOCKTHISUSER             = "このユーザーをブロックする"
    static let BLOCK_USER_SUCCESS        = "このユーザーはブロックされています"
    static let CAMERA                    = "カメラ"
    static let CANCEL                    = "取消"
    static let CANCELED                  = "キャンセル"
    static let CANTMOREPICTURE           = "4つ以上の画像を選択することはできません。"
    static let CHAT_REQUEST              = "チャットリクエスト"
    static let CHOOSE_VIDEO_IMAGE        = "ビデオまたは画像を選択"
    static let COMMENT                   = "コメント"
    static let COMPLETED                 = "完了"
    static let CONFIRM_PASSWORD          = "パスワードを認証する"
    static let CONFIRM_PASSWORD_MATCH    = "パスワードが一致していることを確認してください。"
    static let CONTACT_US                = "お問い合わせ"
    static let CONVERSATION_AVAILABLE    = "チャット可能"
    static let CONVERSATION_REQUEST      = "チャットリクエスト"
    static let CURRENT_PWD               = "受け入れる"
    static let CUSTOMER                  = "概要"
    static let DATE_REQUIRE              = "リクエスト日を選択してください。"
    static let DELETE                    = "削除"
    static let DETAILS_REQUIRE           = "詳細を入力してください。"
    static let DOG_PARK                  = "どこにいる？"
    static let DOYOUWANTTODELETETHISPOST = "この記事を削除しますか？"
    static let EDIT_PROFILE             = "プロファイル編集"
    static let EDIT_YOUR_PET             = "ペット編集します"
    static let EMAIL                     = "Eメール"
    static let EMAIL_REQUIRE             = "メールアドレスを入力"
    static let FAVORITE                  = "お気に入り"
    static let FAVORITELIST              = "お気に入りリスト"
    static let FEMALE                    = "メス"
    static let FOLLOWERS                 = "フォロワー"
    static let FRIEND_LIST               = "友達一覧"
    static let GALLERY                   = "ギャラリー"
    static let HOME                      = "ホーム"
    static let IMAGE_UPLOAD_FAIL         = "画像のアップロードに失敗しました。"
    static let INPUT_CONFIRM_PWD         = "確認パスワードを入力してください"
    static let INPUT_CORRECT_CURRENT_PWD = "正しい現在のパスワードを入力してください。"
    static let INPUT_MATCHED_CONFIRM_PWD = "一致した確認パスワードを入力してください。"
    static let INPUT_NEW_PWD             = "新しいパスワードを入力してください。"
    static let INPUT_PHONE_NUMBER        = "電話番号を入力してください。"
    static let LIKERS                    = "いいね"
    static let LOCATION                  = "場所"
    static let LODGING                   = "宿泊"
    static let LOGOUT                    = "ログアウト"
    static let LOOK_FOR                  = "相談者検索"
    static let MALE                      = "オス"
    static let MESSAGE                   = "チャット"
    static let MOFUTOMO                  = "モフトモ！"
    static let MY_ACCOUNT                = "マイアカウント"
    static let MY_PAGE                   = "マイメニュー"
    static let NEARBYUSER                = "周辺ユーザ"
    static let NETISSUE                  = "ネットワークの問題。"
    static let NEWS                      = "ニュース"
    static let NEW_PWD                   = "新しいパスワード"
    static let NEW_PWD_CONFIRM           = "新しいパスワードの確認"
    static let NEW_REQUEST               = "新申請"
    static let NOTIFICATION              = "通知"
    static let NO_ARTICLE_PREVIOUS_POST  = "あなたが以前に投稿したり、フォローしている記事がありません。"
    static let NO_COMMENT                = "コメントはまだありません。"
    static let NO_DATA                   = "読み取るデータはありません。"
    static let NO_POST_DATA              = "投稿されたデータはありません。"
    static let OVER_VIEW                 = "概要"
    static let PAID                      = "支払った"
    static let PASSWORD                  = "パスワード"
    static let PASSWORD_INCORRECT        = "正しくないパスワード。"
    static let PASSWORD_REQUIRE          = "パスワードを入力してください。"
    static let PAYMENT                   = "支払い"
    static let PENDING                   = "保留中"
    static let PETBIRTHDAY               = "ペット生年月日"
    static let PETNAME                   = "ペット名前"
    static let PET_ADD                   = "ペットを追加"
    static let PET_AGE_REQUIRE           = "ペットの年齢が必要"
    static let PET_AVATAR_REQUIRE        = "ペット画像が必要"
    static let PET_EDIT                  = "ペット編集"
    static let PET_KIND_REQUIRE          = "ペット種別選択"
    static let PET_NAME_REQUIRE          = "ペットの名前が必要"
    static let PET_REGISTER              = "ペット登録"
    static let POST                      = "投稿"
    static let POST_TEXT_REQUIRE         = "投稿テキストを入力してください。"
    static let PRICE_REQUIRE             = "サービスの価格を入力してください。"
    static let PRIMARY_CUSTODY           = "一次預かり"
    static let PRIVACY                   = "個人情報保護方針"
    static let PRIVACY_KAN                   = "プライバシーポリシー"
    static let PROFILE                   = "プロフィール"
    static let FAVORITE_LOCATION_LIST    = "お気に入り施設一覧"
    static let REFUND                    = "払い戻し"
    static let REGISTER_YOUR_PET         = "ペット登録します"
    static let REJECT                    = "拒絶"
    static let REJECTED                  = "拒否"
    static let REMOVE_THIS_POST          = "この記事を削除しますか？"
    static let REPLY_TEXT_REQUIRE        = "返信テキストを入力してください。"
    static let REPORT                    = "報告"
    static let REPORT_SUCCESS            = "正常に報告されました"
    static let REPORT_THIS_PERSON        = "この人を報告する"
    static let REPORT_THIS_POST          = "この投稿を報告する"
    static let REQUEST_SENT_CANCEL       = "リクエストキャンセル"
    static let REQUEST_SENT_SUCCESS      = "モフトモリクエスト送信済み"
    static let REQUEST_TYPE_REQUIRE      = "リクエストタイプを入力してください。"
    static let RESET_PASSWORD            = "パスワードを再設定する"
    static let SELECT_PET                = "ペットを選択する"
    static let SELECT_POST_IMAGE_VIDEO   = "ポストビデオまたは画像を選択してください。"
    static let SELECT_VALID_DATE         = "有効な日付を選択してください"
    static let SEND_NEW_REQUEST          = "新しい要求を送る"
    static let SENT                      = "送信"
    static let SERVICE_DETAIL            = "サービスの詳細"
    static let SERVICE_PRICE             = "サービス価格"
    static let SERVICE_PROVIDER          = "サービスプロバイダ"
    static let SERVICE_TYPE              = "サービスの種類"
    static let SETTINGS                  = "設定"
    static let SIGNIN                    = "ログイン"
    static let SIGNUP                    = "会員登録"
    static let TAKEWALK                  = "不在時散歩"
    static let TERMS                     = "利用規約"
    static let TERMS_AGREE               = "利用規約とプライバシーポリシーに同意しますか?"
    static let TIMELINE                  = "タイムライン"
    static let TWEET                     = "相談質問"
    static let UNBLOCKUSER               = "ブロックを解除"
    static let UNFRIEND                  = "友達を外す"
    static let UPDATE_PET                = "ペット更新"
    static let UPDATE_SUCCESS            = "正常な更新"
    static let USERNAME                  = "ユーザー名"
    static let USERNAME_EXIST            = "ユーザー名は既に存在します。"
    static let USERNAME_NONE_EXIST       = "ユーザー名は存在しません。"
    static let USERNAME_REQUIRE          = "ユーザー名を入力してください。"
    static let USER_EMAIL_EXIST          = "ユーザーメールが既に存在します。"
    static let USER_EMAIL_NOT_EXIST      = "ユーザーのメールが存在しません"
    static let VALID_EMAIL_REQUIRE       = "正しいメールアドレスを入力してください。"
    static let VALID_INFORMATION_REQUIRE = "正確な情報を入力してください。"
    static let WALKING_AGENCY            = "散歩代行"
    static let WHATS_ON_YOUR_MIND        = "何を考えているの?"
    static let YEAR                      = "歳"
    static let YOUCANTLIKEYOURPOST       = "あなたは、あなたの投稿が好きできません"
    static let YOUCANTREPORTYOURPOST     = "自分の投稿を直接報告することができません"
    static let MAP = "地図"
    static let ETC = "その他"
    static let TOTAL_NOTI = "全ユーザーへの通知"
}

struct Constants {
    static let PROGRESS_COLOR = UIColor.black
    static let SAVE_ROOT_PATH = "save_root"
    static let SCREEN_HEIGHT = UIScreen.main.bounds.height
    static let SCREEN_WIDTH = UIScreen.main.bounds.width
    static let TERMS_LINK = "https://map-app.tutu-sol.com/terms.pdf"
    static let PRIVACY_LINK = "https://map-app.tutu-sol.com/privacy.pdf"
    static let GOOGLE_API_KEY = "AIzaSyDigbXIHJ2q5mQnubsKz4dxLek8heVX69c"
    static let DIRECTION_API_KEY = "AIzaSyDs247oW0HsnxfIA86Ar9IQYI1bC4TwnAg"
    static let ONE_WEEK_TIMESTAMP  = 604800
    static let uuid = UIDevice.current.identifierForVendor?.uuidString
}

struct COLORS {
    static let PRIMARY = UIColor(named: "color_primary")
    static let PRIMARYLIGHT = UIColor(named: "color_primary_light")
}

struct SettingOptions {
    static let setting_section = [Messages.ACCOUNT, Messages.ETC]
    static let settingOption_section1 = [Messages.LOGIN]
    static let settingOption_section2 = [Messages.TERMS, Messages.PRIVACY_KAN, Messages.CONTACT_US, Messages.LOGOUT]
    static let settingOption_section3 = [Messages.TERMS, Messages.PRIVACY_KAN, Messages.CONTACT_US]
}

enum LikeType: Int {
    case unlike = 0
    case like = 1
}

enum NoteActionType: Int {
    case upload = 0
    case update = 1
}

enum LocationRequestType: Int{
    case all_location = 0
    case my_favorite_location = 1
}


